# 아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO
# 아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF
# 총 주문량이 큰 순서대로 조회-> DESC
SELECT A.FLAVOR
FROM FIRST_HALF A, ICECREAM_INFO B
WHERE A.FLAVOR=B.FLAVOR AND A.TOTAL_ORDER >3000 AND B.INGREDIENT_TYPE="fruit_based"
ORDER BY A.TOTAL_ORDER DESC