# ONLINE_SLAE과 OFFLINE_SALE 테이블의 값을 UNION 함수를 이용하여 합쳐주기
(SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE, PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE AS N
WHERE SALES_DATE LIKE "2022-03%"
UNION
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE, PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE AS OFF
WHERE SALES_DATE LIKE "2022-03%")
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC